export const apiMocks = {
  productsAllPage1: {
    limit: 12,
    products: [
      {
        brand: "Dry Rose",
        category: "groceries",
        description:
          "Dry Rose Flower Powder Gulab Powder 50 Gram • Treats Wounds",
        discountPercentage: 13.58,
        id: 25,
        images: [Array],
        price: 70,
        rating: 4.87,
        stock: 47,
        thumbnail: "https://cdn.dummyjson.com/product-images/25/thumbnail.jpg",
        title: "Gulab Powder 50 Gram",
      },
      {
        brand: "Boho Decor",
        category: "home-decoration",
        description:
          "Boho Decor Plant Hanger For Home Wall Decoration Macrame Wall Hanging Shelf",
        discountPercentage: 17.86,
        id: 26,
        images: [Array],
        price: 41,
        rating: 4.08,
        stock: 131,
        thumbnail: "https://cdn.dummyjson.com/product-images/26/thumbnail.jpg",
        title: "Plant Hanger For Home",
      },
      {
        brand: "Flying Wooden",
        category: "home-decoration",
        description:
          "Package Include 6 Birds with Adhesive Tape Shape: 3D Shaped Wooden Birds Material: Wooden MDF, Laminated 3.5mm",
        discountPercentage: 15.58,
        id: 27,
        images: [Array],
        price: 51,
        rating: 4.41,
        stock: 17,
        thumbnail: "https://cdn.dummyjson.com/product-images/27/thumbnail.webp",
        title: "Flying Wooden Bird",
      },
      {
        brand: "LED Lights",
        category: "home-decoration",
        description:
          "3D led lamp sticker Wall sticker 3d wall art light on/off button  cell operated (included)",
        discountPercentage: 16.49,
        id: 28,
        images: [Array],
        price: 20,
        rating: 4.82,
        stock: 54,
        thumbnail: "https://cdn.dummyjson.com/product-images/28/thumbnail.jpg",
        title: "3D Embellishment Art Lamp",
      },
      {
        brand: "luxury palace",
        category: "home-decoration",
        description:
          "Handcraft Chinese style art luxury palace hotel villa mansion home decor ceramic vase with brass fruit plate",
        discountPercentage: 15.34,
        id: 29,
        images: [Array],
        price: 60,
        rating: 4.44,
        stock: 7,
        thumbnail: "https://cdn.dummyjson.com/product-images/29/thumbnail.webp",
        title: "Handcraft Chinese style",
      },
      {
        brand: "Golden",
        category: "home-decoration",
        description:
          "Attractive DesignMetallic materialFour key hooksReliable & DurablePremium Quality",
        discountPercentage: 2.92,
        id: 30,
        images: [Array],
        price: 30,
        rating: 4.92,
        stock: 54,
        thumbnail: "https://cdn.dummyjson.com/product-images/30/thumbnail.jpg",
        title: "Key Holder",
      },
      {
        brand: "Furniture Bed Set",
        category: "furniture",
        description:
          "Mornadi Velvet Bed Base with Headboard Slats Support Classic Style Bedroom Furniture Bed Set",
        discountPercentage: 17,
        id: 31,
        images: [Array],
        price: 40,
        rating: 4.16,
        stock: 140,
        thumbnail: "https://cdn.dummyjson.com/product-images/31/thumbnail.jpg",
        title: "Mornadi Velvet Bed",
      },
      {
        brand: "Ratttan Outdoor",
        category: "furniture",
        description:
          "Ratttan Outdoor furniture Set Waterproof  Rattan Sofa for Coffe Cafe",
        discountPercentage: 15.59,
        id: 32,
        images: [Array],
        price: 50,
        rating: 4.74,
        stock: 30,
        thumbnail: "https://cdn.dummyjson.com/product-images/32/thumbnail.jpg",
        title: "Sofa for Coffe Cafe",
      },
      {
        brand: "Kitchen Shelf",
        category: "furniture",
        description:
          "3 Tier Corner Shelves | 3 PCs Wall Mount Kitchen Shelf | Floating Bedroom Shelf",
        discountPercentage: 17,
        id: 33,
        images: [Array],
        price: 700,
        rating: 4.31,
        stock: 106,
        thumbnail: "https://cdn.dummyjson.com/product-images/33/thumbnail.jpg",
        title: "3 Tier Corner Shelves",
      },
      {
        brand: "Multi Purpose",
        category: "furniture",
        description:
          "Very good quality plastic table for multi purpose now in reasonable price",
        discountPercentage: 4,
        id: 34,
        images: [Array],
        price: 50,
        rating: 4.01,
        stock: 136,
        thumbnail: "https://cdn.dummyjson.com/product-images/34/thumbnail.jpg",
        title: "Plastic Table",
      },
      {
        brand: "AmnaMart",
        category: "furniture",
        description:
          "Material: Stainless Steel and Fabric  Item Size: 110 cm x 45 cm x 175 cm Package Contents: 1 Storage Wardrobe",
        discountPercentage: 7.98,
        id: 35,
        images: [Array],
        price: 41,
        rating: 4.06,
        stock: 68,
        thumbnail: "https://cdn.dummyjson.com/product-images/35/thumbnail.jpg",
        title: "3 DOOR PORTABLE",
      },
      {
        brand: "Professional Wear",
        category: "tops",
        description:
          "Cotton Solid Color Professional Wear Sleeve Shirt Womens Work Blouses Wholesale Clothing Casual Plain Custom Top OEM Customized",
        discountPercentage: 10.89,
        id: 36,
        images: [Array],
        price: 90,
        rating: 4.26,
        stock: 39,
        thumbnail: "https://cdn.dummyjson.com/product-images/36/thumbnail.jpg",
        title: "Sleeve Shirt Womens",
      },
    ],
    skip: 0,
    total: 20,
  },
  productsAllPage2: {
    limit: 12,
    products: [
      {
        brand: "LouisWill",
        category: "sunglasses",
        description:
          "LouisWill Men Sunglasses Polarized Sunglasses UV400 Sunglasses Day Night Dual Use Safety Driving Night Vision Eyewear AL-MG Frame Sun Glasses with Free Box for Drivers",
        discountPercentage: 11.27,
        id: 85,
        images: [Array],
        price: 50,
        rating: 4.98,
        stock: 92,
        thumbnail: "https://cdn.dummyjson.com/product-images/85/thumbnail.jpg",
        title: "LouisWill Men Sunglasses",
      },
      {
        brand: "Car Aux",
        category: "automotive",
        description:
          "Bluetooth Aux Bluetooth Car Aux Car Bluetooth Transmitter Aux Audio Receiver Handfree Car Bluetooth Music Receiver Universal 3.5mm Streaming A2DP Wireless Auto AUX Audio Adapter With Mic For Phone MP3",
        discountPercentage: 10.56,
        id: 86,
        images: [Array],
        price: 25,
        rating: 4.57,
        stock: 22,
        thumbnail: "https://cdn.dummyjson.com/product-images/86/thumbnail.jpg",
        title: "Bluetooth Aux",
      },
      {
        brand: "W1209 DC12V",
        category: "automotive",
        description:
          "Both Heat and Cool Purpose, Temperature control range; -50 to +110, Temperature measurement accuracy; 0.1, Control accuracy; 0.1",
        discountPercentage: 11.3,
        id: 87,
        images: [Array],
        price: 40,
        rating: 4.54,
        stock: 37,
        thumbnail: "https://cdn.dummyjson.com/product-images/87/thumbnail.jpg",
        title: "t Temperature Controller Incubator Controller",
      },
      {
        brand: "TC Reusable",
        category: "automotive",
        description:
          "TC Reusable Silicone Magic Washing Gloves with Scrubber, Cleaning Brush Scrubber Gloves Heat Resistant Pair for Cleaning of Kitchen, Dishes, Vegetables and Fruits, Bathroom, Car Wash, Pet Care and Multipurpose",
        discountPercentage: 3.19,
        id: 88,
        images: [Array],
        price: 29,
        rating: 4.98,
        stock: 42,
        thumbnail: "https://cdn.dummyjson.com/product-images/88/thumbnail.jpg",
        title: "TC Reusable Silicone Magic Washing Gloves",
      },
      {
        brand: "shock absorber",
        category: "motorcycle",
        description:
          "150cc 4-Stroke Motorcycle Automatic Motor Gas Motorcycles Scooter motorcycles 150cc scooter",
        discountPercentage: 3.34,
        id: 93,
        images: [Array],
        price: 1050,
        rating: 4.84,
        stock: 127,
        thumbnail: "https://cdn.dummyjson.com/product-images/93/thumbnail.jpg",
        title: "Automatic Motor Gas Motorcycles",
      },
      {
        brand: "JIEPOLLY",
        category: "motorcycle",
        description:
          "new arrivals Fashion motocross goggles motorcycle motocross racing motorcycle",
        discountPercentage: 3.85,
        id: 94,
        images: [Array],
        price: 900,
        rating: 4.06,
        stock: 109,
        thumbnail: "https://cdn.dummyjson.com/product-images/94/thumbnail.webp",
        title: "new arrivals Fashion motocross goggles",
      },
      {
        brand: "Xiangle",
        category: "motorcycle",
        description:
          "Wholesale cargo lashing Belt Tie Down end Ratchet strap customized strap 25mm motorcycle 1500kgs with rubber handle",
        discountPercentage: 17.67,
        id: 95,
        images: [Array],
        price: 930,
        rating: 4.21,
        stock: 144,
        thumbnail: "https://cdn.dummyjson.com/product-images/95/thumbnail.jpg",
        title: "Wholesale cargo lashing Belt",
      },
      {
        brand: "lightingbrilliance",
        category: "lighting",
        description:
          "Wholesale slim hanging decorative kid room lighting ceiling kitchen chandeliers pendant light modern",
        discountPercentage: 14.89,
        id: 96,
        images: [Array],
        price: 30,
        rating: 4.83,
        stock: 96,
        thumbnail: "https://cdn.dummyjson.com/product-images/96/thumbnail.jpg",
        title: "lighting ceiling kitchen",
      },
    ],
    skip: 12,
    total: 20,
  },
  productsCategoryLaptops: {
    limit: 5,
    products: [
      {
        brand: "Apple",
        category: "laptops",
        description:
          "MacBook Pro 2021 with mini-LED display may launch between September, November",
        discountPercentage: 11.02,
        id: 6,
        images: [Array],
        price: 1749,
        rating: 4.57,
        stock: 83,
        thumbnail: "https://cdn.dummyjson.com/product-images/6/thumbnail.png",
        title: "MacBook Pro",
      },
      {
        brand: "Samsung",
        category: "laptops",
        description:
          "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
        discountPercentage: 4.15,
        id: 7,
        images: [Array],
        price: 1499,
        rating: 4.25,
        stock: 50,
        thumbnail: "https://cdn.dummyjson.com/product-images/7/thumbnail.jpg",
        title: "Samsung Galaxy Book",
      },
      {
        brand: "Microsoft Surface",
        category: "laptops",
        description:
          "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.",
        discountPercentage: 10.23,
        id: 8,
        images: [Array],
        price: 1499,
        rating: 4.43,
        stock: 68,
        thumbnail: "https://cdn.dummyjson.com/product-images/8/thumbnail.jpg",
        title: "Microsoft Surface Laptop 4",
      },
      {
        brand: "Infinix",
        category: "laptops",
        description:
          "Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty",
        discountPercentage: 11.83,
        id: 9,
        images: [Array],
        price: 1099,
        rating: 4.54,
        stock: 96,
        thumbnail: "https://cdn.dummyjson.com/product-images/9/thumbnail.jpg",
        title: "Infinix INBOOK",
      },
      {
        brand: "HP Pavilion",
        category: "laptops",
        description:
          "HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10",
        discountPercentage: 6.18,
        id: 10,
        images: [Array],
        price: 1099,
        rating: 4.43,
        stock: 89,
        thumbnail: "https://cdn.dummyjson.com/product-images/10/thumbnail.jpeg",
        title: "HP Pavilion 15-DK1056WM",
      },
    ],
    skip: 0,
    total: 5,
  },
  productCategories: [
    "smartphones",
    "laptops",
    "fragrances",
    "skincare",
    "groceries",
    "home-decoration",
    "furniture",
    "tops",
    "womens-dresses",
    "womens-shoes",
    "mens-shirts",
    "mens-shoes",
    "mens-watches",
    "womens-watches",
    "womens-bags",
    "womens-jewellery",
    "sunglasses",
    "automotive",
    "motorcycle",
    "lighting",
  ],
  products1: {
    brand: "Apple",
    category: "smartphones",
    description:
      "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
    discountPercentage: 17.94,
    id: 1,
    images: [
      "https://cdn.dummyjson.com/product-images/2/1.jpg",
      "https://cdn.dummyjson.com/product-images/2/2.jpg",
      "https://cdn.dummyjson.com/product-images/2/3.jpg",
      "https://cdn.dummyjson.com/product-images/2/thumbnail.jpg",
    ],
    price: 899,
    rating: 4.44,
    stock: 34,
    thumbnail: "https://cdn.dummyjson.com/product-images/2/thumbnail.jpg",
    title: "iPhone X",
  },
};
